// Copyright 2024 jayvee <jvvcen@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePostM = "post"

// PostM 博文表
type PostM struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    string    `gorm:"column:userID;not null;comment:用户唯一 ID" json:"userID"`                                  // 用户唯一 ID
	PostID    string    `gorm:"column:postID;not null;uniqueIndex:idx_post_postID;comment:博文唯一 ID" json:"postID"`      // 博文唯一 ID
	Title     string    `gorm:"column:title;not null;comment:博文标题" json:"title"`                                       // 博文标题
	Content   string    `gorm:"column:content;not null;comment:博文内容" json:"content"`                                   // 博文内容
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:current_timestamp;comment:博文创建时间" json:"createdAt"`   // 博文创建时间
	UpdatedAt time.Time `gorm:"column:updatedAt;not null;default:current_timestamp;comment:博文最后修改时间" json:"updatedAt"` // 博文最后修改时间
}

// TableName PostM's table name
func (*PostM) TableName() string {
	return TableNamePostM
}
