// Post API 定义，包含博客文章的请求和响应消息

// Copyright 2024 jayvee <jvvcen@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Post) Default() {
}

func (x *CreatePostRequest) Default() {
}

func (x *CreatePostResponse) Default() {
}

func (x *UpdatePostRequest) Default() {
}

func (x *UpdatePostResponse) Default() {
}

func (x *DeletePostRequest) Default() {
}

func (x *DeletePostResponse) Default() {
}

func (x *GetPostRequest) Default() {
}

func (x *GetPostResponse) Default() {
}

func (x *ListPostRequest) Default() {
}

func (x *ListPostResponse) Default() {
}
